### ISSUE TITLE
UnauthorizedAccessException: Access to the path "Library\UnityAssemblies\UnityEngine.xml" is denied.

### ISSUE THREAD

**Issue by wanghuatao** [jarjin/SimpleFramework_NGUI#1]
UnauthorizedAccessException: Access to the path "Library\UnityAssemblies\UnityEngine.xml" is denied.
System.IO.File.Delete (System.String path) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/File.cs:179)
SyntaxTree.VisualStudio.Unity.Bridge.Project.SafeDelete (System.String file)
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilesGenerator.CleanDeployPath ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilesGenerator.DeployUnityAssemblies (SyntaxTree.VisualStudio.Unity.Bridge.UnitySolution solution)
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilesGenerator.GenerateProject ()
SyntaxTree.VisualStudio.Unity.Bridge.Project+<>c__DisplayClass3.<RunOnceOnUpdate>b__2 ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplication.gen.cs:268)

重启unity 跟 clear lua binder 之后也不行

**Comment by jarjin** [comment]
Unity BUG
